[project]
name = "brave-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "André Pont", email = "andrepontde@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.20.0",
    "python-dotenv>=1.1.1",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.0.54",
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
brave-service = "brave_service:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
